version: '3'
services:
  php:
    image: php:fpm-alpine
    volumes:
      - ./src:/var/www/html
      - ./memory.ini:/usr/local/etc/php/conf.d/memory.ini

  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
