version: '3.9'
services:
  chown-sitemap:
    image: php:fpm-alpine
    volumes:
      - sitemap:/var/www/sitemap
    command: chown -R www-data:www-data /var/www/sitemap

  build-ipfs:
    profiles:
      - build
    image: node
    volumes:
      - ipfs:/app
      - ./helia-vite:/src
    command: sh -c "cd /src; npm i; npm run build; cp -r dist/* /app/"

  php:
    user: www-data
    image: php:fpm-alpine
    volumes:
      - ./src:/var/www/html
      - ./settings.ini:/usr/local/etc/php/conf.d/settings.ini
      - sitemap:/var/www/sitemap
    env_file:
      - .env
    depends_on:
      chown-sitemap:
        condition: service_completed_successfully

  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ipfs:/var/www/ipfs
      - sitemap:/var/www/sitemap
    depends_on:
        php:
          condition: service_started

volumes:
  sitemap:
  ipfs: